# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html for more information

# [sncast.dev]                                                 # Define a profile name
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"   # Url of the RPC provider
# accounts_file = "~/.starkli-wallets/deployer/account1.json"    # Path to the file with the account data
# account = "mainuser"                                         # Account from `accounts_file` or default account file that will be used for the transactions
keystore = "~/.starkli-wallets/deployer/dev1.json"             # Path to the keystore file
# wait_params = { timeout = 500, retry_interval = 10 }         # Wait for submitted transaction parameters
# block_explorer = "StarkScan"                                 # Block explorer service used to display links to transaction details

